export const emojis = {
  // Smiley Face Emojis
  slightly_smiling_face: "🙂",
  smiling_face: "😀",
  smiling_face_with_big_eyes: "😃",
  lauging_face_with_smiling_eyes: "😄",
  beaming_face_with_smiling_eyes: "😁",
  grinning_face_with_sweat: "😅",
  grinning_face: "😆",
  rolling_on_the_floor_laughing: "🤣",
  lauging_with_tears: "😂",
  upside_down_face: "🙃",
  winking_face: "😉",
  smiling_face_with_smiling_eyes: "😊",
  smiling_face_with_halo: "😇",
  smiling_face_with_sunglasses: "😎",
  nerdy_face: "🤓",
  face_with_monocle: "🧐",
  partying_face: "🥳",
  //   Emotional Faces Emojis
  smiling_face_with_hearts: "🥰",
  smiling_face_with_heart_eyes: "😍",
  star_struck: "🤩",
  face_blowing_kiss: "😘",
  kissing_face: "😗",
  smiling_face_with_rosy_cheeks: "☺️",
  kissing_face_with_closed_eyes: "😚",
  kissng_face_with_smiling_eyes: "😙",
  smiling_face_with_tears: "🥲",
  //   Costume Faces Emojis
  pile_of_poo: "💩",
  clown: "🤡",
  ogre: "👹",
  goblin: "👺",
  ghost: "👻",
  alien: "👽",
  alien_monster: "👾",
  robot: "🤖",
};
